# 服务名
spring:
  application:
    name: eureka-consumer

# 服务端口号
server:
  port: 2101
  tomcat:
    # tomcat同时处理请求的线程数
    max-threads: 10

eureka:
  instance:
    # 当前服务在注册中心的名字
    appname: eureka-consumer
    prefer-ip-address: true
  client:
    service-url:
      # 注册中心的地址
      defaultZone: http://127.0.0.1:1001/eureka/

feign:
  hystrix:
    # 开启hystrix服务保护功能.默认是线程池隔离模式.默认开启了服务熔断.降级.
    enabled: true







